/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProblemViewerFrame.java
 *
 * Created on 01 6, 11, 8:28:58 PM
 */

package southeastasia;

import southeastasia.game.Problem;

/**
 *
 * @author Enzo
 */
public class ProblemViewerFrame extends javax.swing.JFrame {

    private Problem problem;
    private SoutheastAsiaView server;
    private int playerCode;
    /** Creates new form ProblemViewer */
    public ProblemViewerFrame(Problem p, SoutheastAsiaView server, int playerCode) {
        initComponents();
        problem=p;
        this.server=server;
        this.playerCode=playerCode;
        loadProblem();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        problemNameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        problemDescField = new javax.swing.JTextArea();
        solvedButton = new javax.swing.JButton();
        notSolvedButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        economicPenalty = new javax.swing.JTextField();
        politicalPenalty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        militaryPenalty = new javax.swing.JTextField();
        culturalPenalty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        economicBonus = new javax.swing.JTextField();
        politicalBonus = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        militaryBonus = new javax.swing.JTextField();
        culturalBonus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        problemNameField.setEditable(false);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(southeastasia.SoutheastAsiaApp.class).getContext().getResourceMap(ProblemViewerFrame.class);
        problemNameField.setText(resourceMap.getString("problemNameField.text")); // NOI18N
        problemNameField.setName("problemNameField"); // NOI18N
        problemNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemNameFieldActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        problemDescField.setColumns(20);
        problemDescField.setEditable(false);
        problemDescField.setLineWrap(true);
        problemDescField.setRows(5);
        problemDescField.setName("problemDescField"); // NOI18N
        jScrollPane2.setViewportView(problemDescField);

        solvedButton.setText(resourceMap.getString("solvedButton.text")); // NOI18N
        solvedButton.setName("solvedButton"); // NOI18N
        solvedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solvedButtonActionPerformed(evt);
            }
        });

        notSolvedButton.setText(resourceMap.getString("notSolvedButton.text")); // NOI18N
        notSolvedButton.setName("notSolvedButton"); // NOI18N
        notSolvedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notSolvedButtonActionPerformed(evt);
            }
        });

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        economicPenalty.setText(resourceMap.getString("economicPenalty.text")); // NOI18N
        economicPenalty.setName("economicPenalty"); // NOI18N
        economicPenalty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                economicPenaltyKeyTyped(evt);
            }
        });

        politicalPenalty.setText(resourceMap.getString("politicalPenalty.text")); // NOI18N
        politicalPenalty.setName("politicalPenalty"); // NOI18N
        politicalPenalty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                politicalPenaltyKeyTyped(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        militaryPenalty.setText(resourceMap.getString("militaryPenalty.text")); // NOI18N
        militaryPenalty.setName("militaryPenalty"); // NOI18N
        militaryPenalty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                militaryPenaltyKeyTyped(evt);
            }
        });

        culturalPenalty.setText(resourceMap.getString("culturalPenalty.text")); // NOI18N
        culturalPenalty.setName("culturalPenalty"); // NOI18N
        culturalPenalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                culturalPenaltyActionPerformed(evt);
            }
        });
        culturalPenalty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                culturalPenaltyKeyTyped(evt);
            }
        });

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(culturalPenalty, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(economicPenalty)
                            .addComponent(militaryPenalty)
                            .addComponent(politicalPenalty)))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(culturalPenalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(economicPenalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(militaryPenalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(politicalPenalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel3.setName("jPanel3"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        economicBonus.setText(resourceMap.getString("economicBonus.text")); // NOI18N
        economicBonus.setName("economicBonus"); // NOI18N
        economicBonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                economicBonusKeyTyped(evt);
            }
        });

        politicalBonus.setText(resourceMap.getString("politicalBonus.text")); // NOI18N
        politicalBonus.setName("politicalBonus"); // NOI18N
        politicalBonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                politicalBonusKeyTyped(evt);
            }
        });

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        militaryBonus.setText(resourceMap.getString("militaryBonus.text")); // NOI18N
        militaryBonus.setName("militaryBonus"); // NOI18N
        militaryBonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                militaryBonusKeyTyped(evt);
            }
        });

        culturalBonus.setText(resourceMap.getString("culturalBonus.text")); // NOI18N
        culturalBonus.setName("culturalBonus"); // NOI18N
        culturalBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                culturalBonusActionPerformed(evt);
            }
        });
        culturalBonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                culturalBonusKeyTyped(evt);
            }
        });

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(culturalBonus, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(economicBonus)
                            .addComponent(militaryBonus)
                            .addComponent(politicalBonus)))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(culturalBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(economicBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(militaryBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(politicalBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(solvedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notSolvedButton))
                    .addComponent(problemNameField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(problemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(solvedButton)
                            .addComponent(notSolvedButton)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void problemNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemNameFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_problemNameFieldActionPerformed

    private void solvedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solvedButtonActionPerformed
        server.setSolved(true, playerCode);
        server.sendClientMessage(playerCode, "warn#Your problem was solved!");
        server.updateActionTables();
}//GEN-LAST:event_solvedButtonActionPerformed

    private void notSolvedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notSolvedButtonActionPerformed
        server.setSolved(false, playerCode);
        server.sendClientMessage(playerCode, "warn#Your problem was not solved!");
        server.updateActionTables();
}//GEN-LAST:event_notSolvedButtonActionPerformed

    private void economicPenaltyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_economicPenaltyKeyTyped
        makeChanges();
}//GEN-LAST:event_economicPenaltyKeyTyped

    private void politicalPenaltyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_politicalPenaltyKeyTyped
        makeChanges();
        // TODO add your handling code here:
}//GEN-LAST:event_politicalPenaltyKeyTyped

    private void militaryPenaltyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_militaryPenaltyKeyTyped
        makeChanges();
        // TODO add your handling code here:
}//GEN-LAST:event_militaryPenaltyKeyTyped

    private void culturalPenaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_culturalPenaltyActionPerformed
        // TODO add your handling code here:
        makeChanges();
}//GEN-LAST:event_culturalPenaltyActionPerformed

    private void culturalPenaltyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_culturalPenaltyKeyTyped
        makeChanges();
}//GEN-LAST:event_culturalPenaltyKeyTyped

    private void economicBonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_economicBonusKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_economicBonusKeyTyped

    private void politicalBonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_politicalBonusKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_politicalBonusKeyTyped

    private void militaryBonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_militaryBonusKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_militaryBonusKeyTyped

    private void culturalBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_culturalBonusActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_culturalBonusActionPerformed

    private void culturalBonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_culturalBonusKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_culturalBonusKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ProblemViewerFrame().setVisible(true);
            }
        });
    }

     private void loadProblem()
    {
        culturalPenalty.setText(""+problem.statModifiers.cultural);
        economicPenalty.setText(""+problem.statModifiers.economic);
        militaryPenalty.setText(""+problem.statModifiers.military);
        politicalPenalty.setText(""+problem.statModifiers.political);
        culturalBonus.setText(""+problem.solveModifiers.cultural);
        economicBonus.setText(""+problem.solveModifiers.economic);
        militaryBonus.setText(""+problem.solveModifiers.military);
        politicalBonus.setText(""+problem.solveModifiers.political);

        problemNameField.setText(problem.name);
        problemDescField.setText(problem.description);
    }

    private void makeChanges()
    {
        //does nothing so far; called if a field is edited
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField culturalBonus;
    private javax.swing.JTextField culturalPenalty;
    private javax.swing.JTextField economicBonus;
    private javax.swing.JTextField economicPenalty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField militaryBonus;
    private javax.swing.JTextField militaryPenalty;
    private javax.swing.JButton notSolvedButton;
    private javax.swing.JTextField politicalBonus;
    private javax.swing.JTextField politicalPenalty;
    private javax.swing.JTextArea problemDescField;
    private javax.swing.JTextField problemNameField;
    private javax.swing.JButton solvedButton;
    // End of variables declaration//GEN-END:variables

}
