/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CountryViewerFrame.java
 *
 * Created on 01 6, 11, 9:09:18 PM
 */

package southeastasia;

/**
 *
 * @author Enzo
 */
public class CountryViewerFrame extends javax.swing.JFrame {

    private int playerCode;
    private SoutheastAsiaView server;
    
    /** Creates new form CountryViewerFrame */
    public CountryViewerFrame(int player, SoutheastAsiaView server) {
        initComponents();
        playerCode=player;
        this.server=server;
        loadCountry();
        unsaved.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cultural = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        economic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        military = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        political = new javax.swing.JTextField();
        unsaved = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        agreementArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jLabel1.setName("jLabel1"); // NOI18N

        cultural.setName("cultural"); // NOI18N
        cultural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                culturalActionPerformed(evt);
            }
        });
        cultural.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                culturalKeyTyped(evt);
            }
        });

        jLabel2.setName("jLabel2"); // NOI18N

        economic.setName("economic"); // NOI18N
        economic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                economicKeyTyped(evt);
            }
        });

        jLabel3.setName("jLabel3"); // NOI18N

        military.setName("military"); // NOI18N
        military.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                militaryKeyTyped(evt);
            }
        });

        jLabel4.setName("jLabel4"); // NOI18N

        political.setName("political"); // NOI18N
        political.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                politicalKeyTyped(evt);
            }
        });

        unsaved.setName("unsaved"); // NOI18N

        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setName("jLabel6"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        itemArea.setColumns(20);
        itemArea.setRows(5);
        itemArea.setName("itemArea"); // NOI18N
        itemArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemAreaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(itemArea);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        agreementArea.setColumns(20);
        agreementArea.setRows(5);
        agreementArea.setName("agreementArea"); // NOI18N
        agreementArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agreementAreaKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(agreementArea);

        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(58, 58, 58)))
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cultural, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(economic, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(military, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(political, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                    .addComponent(unsaved, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cultural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(economic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(military, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(political, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unsaved))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void culturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_culturalActionPerformed
        // TODO add your handling code here:
        makeChanges();
}//GEN-LAST:event_culturalActionPerformed

    private void culturalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_culturalKeyTyped
        makeChanges();
}//GEN-LAST:event_culturalKeyTyped

    private void economicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_economicKeyTyped
        makeChanges();
}//GEN-LAST:event_economicKeyTyped

    private void militaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_militaryKeyTyped
        makeChanges();
        // TODO add your handling code here:
}//GEN-LAST:event_militaryKeyTyped

    private void politicalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_politicalKeyTyped
        makeChanges();
        // TODO add your handling code here:
}//GEN-LAST:event_politicalKeyTyped

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        unsaved.setVisible(false);
        //save the changes
        server.getStats(playerCode).cultural=Integer.parseInt(cultural.getText());
        server.getStats(playerCode).economic=Integer.parseInt(economic.getText());
        server.getStats(playerCode).military=Integer.parseInt(military.getText());
        server.getStats(playerCode).political=Integer.parseInt(political.getText());
        server.getStats(playerCode).inventory=itemArea.getText();
        server.getStats(playerCode).agreements=agreementArea.getText();
        server.updateCountryTables();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void itemAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemAreaKeyTyped
        makeChanges();
    }//GEN-LAST:event_itemAreaKeyTyped

    private void agreementAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agreementAreaKeyTyped
        makeChanges();
    }//GEN-LAST:event_agreementAreaKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CountryViewerFrame().setVisible(true);
            }
        });
    }

    private void makeChanges()
    {
        unsaved.setVisible(true);
    }

    private void loadCountry()
    {
        cultural.setText(""+server.getStats(playerCode).cultural);
        economic.setText(""+server.getStats(playerCode).economic);
        military.setText(""+server.getStats(playerCode).military);
        political.setText(""+server.getStats(playerCode).political);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea agreementArea;
    private javax.swing.JTextField cultural;
    private javax.swing.JTextField economic;
    private javax.swing.JTextArea itemArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField military;
    private javax.swing.JTextField political;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel unsaved;
    // End of variables declaration//GEN-END:variables

}
