/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemPanel.java
 *
 * Created on 03 8, 11, 1:40:36 AM
 */
package southeastasia;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collection;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import southeastasia.game.ItemDetails;

/**
 *
 * @author Enzo
 */
public class ItemPanel extends javax.swing.JPanel {

    /** Creates new form ItemPanel */
    

    public ItemPanel() {

        initComponents();
        this.setVisible(true);
        


    }

    public void initButtonsAction(Collection<ItemDetails> id, SoutheastAsiaClientApp seacp, JFrame parent)
    {

        class ItemButtonListener implements ActionListener
        {
            private SoutheastAsiaClientApp seacapp;
            private ItemDetails target;
            private JFrame parent;
            public ItemButtonListener(SoutheastAsiaClientApp seacp, ItemDetails id, JFrame parent)
            {
                seacapp=seacp;
                target=id;
                this.parent=parent;
            }
            public void actionPerformed(ActionEvent e)
            {
                seacapp.setProductTargetted(target.getName());
                seacapp.setActionLock(false);
                seacapp.lockAction();
                parent.dispose();
            }
        }
        jPanel2.removeAll();
        jPanel2.setLayout(new GridLayout((id.size()/3)+1,3));
        jPanel2.setSize(300, ((id.size()/3)+1)*100);
        JButton itb;
        for (ItemDetails i : id) {
            itb=new JButton();
            itb.setIcon(i.getIcon());
            jPanel2.add(itb);
            itb.addActionListener(new ItemButtonListener(seacp, i, parent));
        }
    }

    public void initButtonTrade(Collection<ItemDetails> id, SoutheastAsiaServerStats stats, JFrame parent)
    {

        class ItemButtonListener implements ActionListener
        {
            private SoutheastAsiaServerStats stats;
            private ItemDetails target;
            private JFrame parent;
            public ItemButtonListener(SoutheastAsiaServerStats seacp, ItemDetails id, JFrame parent)
            {
                stats=seacp;
                target=id;
                this.parent=parent;
            }
            public void actionPerformed(ActionEvent e)
            {
                new CountryChooserFrame(stats, target).setVisible(true);
                parent.dispose();
            }
        }
        jPanel2.removeAll();
        jPanel2.setLayout(new GridLayout((id.size()/3)+1,3));
        jPanel2.setSize(300, ((id.size()/3)+1)*100);
        JButton itb;
        for (ItemDetails i : id) {
            itb=new JButton();
            itb.setIcon(i.getIcon());
            jPanel2.add(itb);
            itb.addActionListener(new ItemButtonListener(stats, i, parent));
        }
    }

    public void initButtonsLogo(Collection<ItemDetails> id)
    {
        jPanel2.removeAll();
        jPanel2.setLayout(new GridLayout(id.size()/3+1,3));
        jPanel2.setSize(300, (id.size()/3+1)*100);
        JLabel itb;
        for (ItemDetails i : id) {
            itb=new JLabel();
            itb.setIcon(i.getIcon());
            jPanel2.add(itb);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
