/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemWindow.java
 *
 * Created on 03 8, 11, 1:40:23 AM
 */

package southeastasia;

import java.awt.BorderLayout;
import java.util.Collection;
import southeastasia.game.ItemDetails;

/**
 *
 * @author Enzo
 */
public class ItemWindow extends javax.swing.JFrame {

    /** Creates new form ItemWindow */
    public ItemWindow() {
        initComponents();
        
        setSize(350, 350);
    }
    public void setListenersGather(Collection<ItemDetails> id, SoutheastAsiaClientApp seacapp)
    {
        ItemPanel ip=new ItemPanel();
        ip.initButtonsAction(id, seacapp, this);
        add(ip, BorderLayout.CENTER);
    }
    public void setItemDisplay(Collection<ItemDetails> id)
    {
        ItemPanel ip=new ItemPanel();
        ip.initButtonsLogo(id);
        add(ip, BorderLayout.CENTER);
    }

    public void setItemTraded(Collection<ItemDetails> id, SoutheastAsiaServerStats stats)
    {
        ItemPanel ip=new ItemPanel();
        ip.initButtonTrade(id, stats, this);
        add(ip,BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
